# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-21 15:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chat_core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='createTime',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
    ]
