# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-21 15:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chat_core', '0002_room_createtime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='createTime',
        ),
        migrations.AddField(
            model_name='room',
            name='updateTime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
